// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fozagrcmptfnbnpivdnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvemFncmNtcHRmbmJucGl2ZG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDMwNzUsImV4cCI6MjA3MjYxOTA3NX0.bvRvt1LlleKADqQwNyLxuCLNgO7P3s7HoUFYsLSzot0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});